server:
  port: 7070
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      tomcat:
        max-idle: 10
        max-wait: 50000
        min-idle: 50
        initial-size: 5
      url: jdbc:mysql://localhost:3306/java_utils?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: root
dubbo:
  application:
    name: springboot-dubbo-demo #应用名
  registry:
    address: zookeeper://127.0.0.1 #zookeeper地址
    port: 2181 #提供注册的端口
  protocol:
    name: dubbo
    port: 20890 #dubbo服务暴露的端口
  scan:
    base-packages: com.example.dubbo_demo.dubbo.service.impl #扫描的包名
